version: '3.4'

services:
  microserviceclientes:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  microserviceempleados:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microservicepedidos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  microserviceproductos:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

